# This workflow will build a .NET MAUI Android project and produce a signed APK

name: MAUI 9 Build(CI/CD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup keystore
        run: |
         echo "${{ secrets.KEYSTORE_FILE }}" > quickbill.keystore.asc 
         gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch quickbill.keystore.asc > quickbill.keystore

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Java 17 (for Android)
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17


      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build QuickBill/QuickBill.csproj -c Release -f net9.0-android /p:AndroidSigningKeyStore=quickbill.keystore /p:AndroidSigningKeyAlias=quickbill /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD_ALIAS }}" --no-restore
   
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
           path: |
               ./**/*.aab
               ./**/*.apk

    
