# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MAUI 9 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Android
      run: dotnet build QuickBill/QuickBill.csproj -c Release -f net9.0-android  --no-restore
    # - name: Build Ios
    #   run: dotnet build QuickBill/QuickBill.csproj -c Release -f net9.0-ios  --no-restore
  
