# This workflow will build a .NET MAUI Android project and produce a signed APK

name: MAUI 9 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Java 17 (for Android)
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: 17


      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build QuickBill/QuickBill.csproj -c Release -f net9.0-android

    
